name: 'Build'

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js LTS
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: pnpm    
    - name: Build
      run: pnpm run build
    - name: Upload packages build artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish.firefox.zip
        path: publish.firefox.zip
        retention-days: 1
